//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CertificateAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class cert
    {
        public string HostName { get; set; }
        public int RequestId { get; set; }
        public int status { get; set; }
        public string CreationDate { get; set; }
        public Nullable<System.DateTime> ExpiredDate { get; set; }
        public string CertFlag { get; set; }
        public string Issuedby { get; set; }
        public string serialnumber { get; set; }
    }
}
