//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CertificateAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Error_Log
    {
        public int ID { get; set; }
        public string HostName { get; set; }
        public Nullable<int> Request { get; set; }
        public string ErrorMessage { get; set; }
        public string CreateDate { get; set; }
    }
}
