//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CertificateAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class signature
    {
        public string uuid { get; set; }
        public string fscadate { get; set; }
        public string hash { get; set; }
        public byte[] timestamp { get; set; }
        public string ldtdisk { get; set; }
        public string hwaddr { get; set; }
        public string hostname { get; set; }
        public Nullable<System.DateTime> signtime { get; set; }
        public Nullable<System.DateTime> host_time { get; set; }
        public string username { get; set; }
    }
}
